### ISSUE TITLE
Unable to locate the file: gallery_model.php

### ISSUE THREAD

**Issue by Rosha** [mrjamiebowman/FUEL-CMS-Photo-Gallery#1]
thank you for your module , I have this error after installation  
Unable to locate the file: gallery_model

**Comment by JBWebServices** [comment]
Hey, sorry, I haven't been working with Fuel anymore. Do you still need any help with this?

**Comment by Rosha** [comment]
ok, thank you I have fixed all errors in this module 
thanks for your module
